feat: get all fields required for POST request
EyeSeeTea/predictor-extended-app-dev pull request #16
Opened 2024-03-01 19:49 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/3k6nam5?comment=90080010899572

### :memo: Implementation

- **Problem**: `organisationUnitDescendants` property in missing in the POST request to save the predictor
- **Solution**: We get the fields using `$owner` filter property

### :art: Screenshots

### :fire: Testing
`REACT_APP_DHIS2_BASE_URL=https://dev.eyeseetea.com/who-dev-238/`

2024-03-14 13:46 UTC, nshandra requested changes

2024-03-14 13:46 UTC, nshandra commented on src/data/PredictorD2ApiRepository.ts
> +                fields: { ...predictorFields, $owner: true },
If im not mistaken, `$owner: true` is added for the `organisationUnitDescendants` field.
Why not add it to the `predictorFields` const?
Same for line 77.

2024-03-14 13:46 UTC, nshandra commented on src/data/PredictorD2ApiRepository.ts
> +                return { ...item, scheduling, organisationUnitDescendants: "DESCENDANTS" };
So, `organisationUnitDescendants` is missing in `D2PredictorSchema` definition.
This means that even when the `organisationUnitDescendants` property exists in `item`, TS will complain that its missing.
Your fix is a hard-coded value, what about the `organisationUnitDescendants: "SELECTED"` cases?

Same for line 89.

2024-03-18 13:41 UTC, deeonwuli commented on src/data/PredictorD2ApiRepository.ts
> +                return { ...item, scheduling, organisationUnitDescendants: "DESCENDANTS" };
i'm only using the hard-coded value "DESCENDANTS" because all the predictors in the dev instance have the `organisationUnitDescendants` property set to "DESCENDANTS". i ran this by @tokland to confirm if using a default value would be fine

2024-03-18 15:40 UTC, nshandra commented on src/data/PredictorD2ApiRepository.ts
> +                return { ...item, scheduling, organisationUnitDescendants: "DESCENDANTS" };
Ok then. Marking as resolved.

2024-03-20 07:54 UTC, nshandra approved these changes
@ifoche, the review is done.

2024-06-03 10:26 UTC, merged